dfds/selfservice-api

- Makefile
- azure-pipelines.yml
closes dfds/cloudplatform/issues/1822
None :)
> Split cd step up in selfservice api pipelines

- k8s/deployment.yml
Adds reference to newly created secret in Kubernetes for 'selfservice-api-dataplatform'.
> Added secretRef for selfservice-api-dataplatform

- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_changing_kafka_topic_description_as_NON_member_of_owning_capability.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_changing_kafka_topic_description_as_member_of_owning_capability.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_changing_kafka_topic_description_with_invalid_input_as_member_of_owning_capability.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_deleting_a_private_kafka_topic_as_NON_member_of_owning_capability.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_deleting_a_private_kafka_topic_as_cloud_engineer.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_deleting_a_private_kafka_topic_as_member_of_owning_capability.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_deleting_a_public_kafka_topic_as_NON_member_of_owning_capability.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_deleting_a_public_kafka_topic_as_cloud_engineer.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_deleting_a_public_kafka_topic_as_member_of_owning_capability.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_getting_private_topics_as_a_cloud_engineer.cs
- src/SelfService.Tests/Infrastructure/Api/KafkaTopicRoutes/when_getting_public_topics_as_a_cloud_engineer.cs
- src/SelfService.Tests/Infrastructure/Api/MembershipApplicationRoutes/when_getting_membership_application_approvals_as_NON_member.cs
- src/SelfService.Tests/Infrastructure/Api/MembershipApplicationRoutes/when_getting_membership_application_approvals_that_does_NOT_exist.cs
- src/SelfService.Tests/Infrastructure/Api/MembershipApplicationRoutes/when_getting_membership_application_for_another_applicant_as_NON_member.cs
- src/SelfService.Tests/Infrastructure/Api/MembershipApplicationRoutes/when_getting_membership_application_that_does_NOT_exist.cs
- src/SelfService/Application/MembershipApplicationService.cs
- src/SelfService/Domain/Services/MembershipApplicationDomainService.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/System/SystemController.cs
closes dfds/cloudplatform/issues/1835
partially 
This is a simple change, removing the first few warnings.
> Remove async where not needed

- src/SelfService.Tests/SelfService.Tests.csproj
- src/SelfService/SelfService.csproj
closes dfds/cloudplatform/issues/1849
It has been done!
> Enabled warnings as errors

- Makefile
- setup-pre-commit-hook.sh
closes dfds/cloudplatform/issues/1848
2 steps have been added to the makefile
- run setup
- run pre-commit
> Created script for setting up pre commit hook

- fake_dependencies/confluent-gateway/FakeConfluentGateway.App/Program.cs
closes dfds/cloudplatform/issues/1904
title
> Problematic charts input added to fakeconfluentcloud

- fake_dependencies/confluent-gateway/FakeConfluentGateway.App/Program.cs
closes dfds/cloudplatform/issues/1947
I did copy paste of the type, I think it is a fine solution for mock/test code. 
Confirmed selfservice api running
Confirmed fake confluent gateway running
> Removed dependency on selfservice api in fake confluent cloud

- src/SelfService.Tests/Infrastructure/Persistence/TestECRRepositoryRepository.cs
- src/SelfService/Domain/Models/IECRRepositoryRepository.cs
- src/SelfService/Domain/Services/ECRRepositoryService.cs
- src/SelfService/Domain/Services/IECRRepositoryService.cs
- src/SelfService/Infrastructure/Persistence/ECRRepositoryRepository.cs
closes dfds/cloudplatform/issues/2021
depends on #57 
This PR adds a service that can synchronize AWS and Db state, where an environment variable determines if it gets executed or not. Default value is to not update, but simply write the differences
> Added syncing of ecr repositories with aws state

- k8s/deployment.yml
issue: https://github.com/dfds/cloudplatform/issues/2047
> Updated gendis image repo

- db/migrations/20230911131855_add-table-for-ecr-repos.sql
- db/migrations/20230915103854_make_repo_name_unique.sql
- k8s/deployment.yml
- src/SelfService/Domain/Models/IECRRepositoryRepository.cs
- src/SelfService/Domain/Services/ECRRepositoryService.cs
- src/SelfService/Domain/Services/IECRRepositoryService.cs
- src/SelfService/Infrastructure/Api/ECRRepositories/ECRRepositoriesController.cs
- src/SelfService/Infrastructure/Persistence/ECRRepositoryRepository.cs
- src/SelfService/Properties/launchSettings.json
closes dfds/cloudplatform/issues/2038
Originally only a task for making ecr repo feature work locally, I have also added some cleanup, nicer error handling and UNIQUE constraint to `RepositoryName`, since running locally it was now possible to make duplicates.
> ECR Repository Clean up

- .github/workflows/shared-env-develop.yml
closes dfds/cloudplatform/issues/2049
> Added pipeline for dev environment

- src/SelfService/Infrastructure/BackgroundJobs/CheckPendingCapabilityDeletions.cs
closes dfds/cloudplatform/issues/2063
Same solution as seen in ECR repository synchronizer scheduled service
> wrapped service call with try catch to prevent crash

- src/SelfService/Domain/Services/ECRRepositoryService.cs
closes dfds/cloudplatform/issues/2067
improved error handling so that we actually get to see what the exception is
> now logging instead of attempting deletion

- src/SelfService.Tests/Application/TestAwsAccountApplicationService.cs
- src/SelfService.Tests/Application/TestCapabilityApplicationService.cs
- src/SelfService.Tests/Builders/A.cs
- src/SelfService.Tests/Builders/CapabilityApplicationServiceBuilder.cs
- src/SelfService.Tests/TestDoubles/StubCapabilityRepository.cs
- src/SelfService/Application/CapabilityApplicationService.cs
- src/SelfService/Application/ICapabilityApplicationService.cs
- src/SelfService/Domain/Exceptions/InvalidJsonMetadataException.cs
- src/SelfService/Domain/Exceptions/InvalidJsonSchemaException.cs
- src/SelfService/Domain/Models/Capability.cs
- src/SelfService/Domain/Models/ICapabilityRepository.cs
- src/SelfService/Domain/Services/AuthorizationService.cs
- src/SelfService/Domain/Services/IAuthorizationService.cs
- src/SelfService/Domain/Services/SelfServiceJsonSchemaService.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityDetailsApiResource.cs
- src/SelfService/Infrastructure/Api/Capabilities/SetCapabilityMetadataRequest.cs
- src/SelfService/Infrastructure/Api/ECRRepositories/ECRRepositoriesController.cs
- src/SelfService/Infrastructure/Api/JsonSchema/SelfServiceJsonSchemaController.cs
- src/SelfService/Infrastructure/Persistence/CapabilityRepository.cs
closes dfds/cloudplatform/issues/2084
Also fixed issue where json meta data wasn't validated fully when added
Also enabled add schema endpoint
> Adding endpoints for setting and getting capability metadata

- db/migrations/20231005143329_add_requested_at_column.sql
- db/seed/ECRRepository.csv
- src/SelfService.Tests/Builders/ECRRepositoryBuilder.cs
- src/SelfService/Domain/Models/ECRRepository.cs
- src/SelfService/Domain/Services/ECRRepositoryService.cs
- src/SelfService/Infrastructure/Persistence/ECRRepositoryRepository.cs
closes dfds/cloudplatform/issues/2125
Double Transactional Boundary means it just doesnt work, so removed the ones that were incorrectly placed inside of the repository.
While debugging what was wrong, I was missing someway of seeing which ecr repositories had been requested and when so I have also added a RequestedAt column.
> Hotfix: ECR repositories not being stored in database

- chart/.helmignore
- chart/Chart.yaml
- chart/templates/_helpers.tpl
- chart/templates/_val.tpl
- chart/templates/deployment.yaml
- chart/templates/ingress.yaml
- chart/templates/service.yaml
- chart/templates/serviceaccount.yaml
- chart/values.yaml
closes dfds/cloudplatform/issues/2014
> Added Helm chart

- src/SelfService/Application/DeactivatedMemberCleanerApplicationService.cs
closes dfds/cloudplatform/issues/2221
small change with a big impact
will wait until monday to actually merge it in, because although there should be sufficient checks in place in the code, it's still kinda scary
> enable deletion of users who are not found in Azure AD

- src/SelfService.Tests/Infrastructure/Api/TestRequestParser.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
- src/SelfService/Infrastructure/Api/RequestParser.cs
closes dfds/cloudplatform/issues/2202
Not super pretty, but think its neat
> added ability to generically parse strings to ValueObject ids

- src/SelfService/Application/DeactivatedMemberCleanerApplicationService.cs
- src/SelfService/Application/IDeactivatedMemberCleanerApplicationService.cs
- src/SelfService/Configuration/Domain.cs
- src/SelfService/Infrastructure/BackgroundJobs/RemoveDeactivatedMemberships.cs
closes dfds/cloudplatform/issues/2235
HOTFIX
I wasn't properly comitting transactions to the db
> 2235 add transactionalboundary to the deactivatedmembershipcleanerapplicationservice

- src/SelfService.Tests/Builders/A.cs
- src/SelfService.Tests/Builders/CapabiltyRequestBuilder.cs
- src/SelfService.Tests/Infrastructure/Api/TestCapabilityCreation.cs
Do we want to have tests like this
> Add test for invitations created upon capability creation

- src/SelfService/Domain/Models/ValueObjectGuid.cs
closes dfds/cloudplatform/issues/2234
Let's be consistent in our dash use
> changed default formatter

- db/migrations/20231004093000_remove_ecr_repositoryname.sql
I forgot to save the existing data.
Luckily a bug occurred and nothing was persisted.
Saved by the bell, I guess.
> Hotfix: Remember to actually store the right names

- .config/dotnet-tools.json
- .github/workflows/check_pr_formatting.yaml
closes dfds/cloudplatform/issues/2248
None
> Add formatting check to pipeline

- src/SelfService/Infrastructure/Persistence/SelfServiceDbContext.cs
- src/SelfService/Logging.cs
closes dfds/cloudplatform/issues/2254
nothing
> set logging level to information, set database logging level to warning

- chart/templates/deployment.yaml
- k8s/deployment.yml
closes dfds/cloudplatform/issues/2249
we didnt have any readiness probe 😅
> added readiness and liveness probes

- src/SelfService/Program.cs
closes dfds/cloudplatform/issues/2256
none
> removed serilog request spam

- src/SelfService/Application/PlatformDataApiRequesterService.cs
closes dfds/cloudplatform/issues/2286
None
> Do not assume timestamp ordering

- src/SelfService/Application/PlatformDataApiRequesterService.cs
closes dfds/cloudplatform/issues/2286
This was a silly mistake
> Lets also compare correctly

- src/SelfService/Application/InvitationApplicationService.cs
closes dfds/cloudplatform/issues/2305
Also changed use of logger to match how it is done other places.
> Fixed invitation description

- fake_dependencies/platform-data-api/FakePlatformDataApi.App/Program.cs
- src/SelfService/Application/PlatformDataApiRequesterService.cs
closes dfds/cloudplatform/issues/2286
Tried before, now trying a different ordering-mechanic.
If this fails, we'll do it in the frontend
> try another ordering

- src/SelfService.Tests/Application/TestPlatformDataApiRequesterService.cs
- src/SelfService.Tests/HttpHelper.cs
- src/SelfService.Tests/Infrastructure/Api/PrometheusClient/TestResultParsing.cs
- src/SelfService/Application/PlatformDataApiRequesterService.cs
closes dfds/cloudplatform/issues/2312
nuthin
> Added platform data api timestamps ordering

- src/SelfService/Application/MembershipApplicationService.cs
ad-hoc bug. was causing problems for @SEQUOIIA but not me :thinking: 
none
> fixed params in logger statement

- src/SelfService/Configuration/Domain.cs
- src/SelfService/Domain/Queries/IAwsAccountIdQuery.cs
- src/SelfService/Domain/Services/AuthorizationService.cs
- src/SelfService/Domain/Services/IAuthorizationService.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityDetailsApiResource.cs
- src/SelfService/Infrastructure/Api/Teams/TeamController.cs
- src/SelfService/Infrastructure/Persistence/Queries/AwsAccountIdQuery.cs
closes dfds/cloudplatform/issues/2288
> now returning aws account id

- src/SelfService/Domain/Models/KafkaTopicId.cs
closes dfds/cloudplatform/issues/2417
> preserve dashes when to string

- db/migrations/20240110102210_add_schema_version_column.sql
- db/seed/MessageContract.csv
- src/SelfService.Tests/Builders/MessageContractBuilder.cs
- src/SelfService/Application/IKafkaTopicApplicationService.cs
- src/SelfService/Application/KafkaTopicApplicationService.cs
- src/SelfService/Domain/Events/NewMessageContractHasBeenRequested.cs
- src/SelfService/Domain/Models/MessageContract.cs
- src/SelfService/Infrastructure/Api/Kafka/KafkaTopicController.cs
- src/SelfService/Infrastructure/Persistence/SelfServiceDbContext.cs
closes dfds/cloudplatform/issues/2470
I am trying to do the addition of versions little by little. Later on I want to add schema version to the dfds envelope and actually allow multiple versions in the frontend.
> added new column schemaversion

- src/SelfService/Application/IKafkaTopicApplicationService.cs
- src/SelfService/Application/KafkaTopicApplicationService.cs
- src/SelfService/Domain/Models/MessageContractSchema.cs
- src/SelfService/Infrastructure/Api/Kafka/KafkaTopicController.cs
- src/SelfService/Infrastructure/Persistence/Converters/MessageContractSchemaConverter.cs
closes dfds/cloudplatform/issues/2467
> updated dfds envelope expectations and now forces this envelope to incoming schemas

- src/SelfService.Tests/Comparers/CapabilityComparer.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/Capabilities/MessageContractApiResource.cs
Every time you add a field you have to add it everywhere, i only added it somewhere.
> added missing schema version

- src/SelfService.Tests/Application/TestMessageContractValidation.cs
- src/SelfService/Application/KafkaTopicApplicationService.cs
- src/SelfService/Domain/Exceptions/InvalidMessageContractEnvelopeException.cs
- src/SelfService/Domain/Exceptions/InvalidMessageContractRequestException.cs
- src/SelfService/Domain/Models/MessageContractSchema.cs
- src/SelfService/Infrastructure/Api/Kafka/KafkaTopicController.cs
closes dfds/cloudplatform/issues/2504
To make sure its easy for the frontend to react to bad request I have made the flow better.
> Made naming more consistent, made exception handling more precise

- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
closes dfds/cloudplatform/issues/2513
None
> Allow optional capability tags

- db/seed/SelfServiceJsonSchema.csv
An attempt at making sure local development looks as production
> Aligning according to the time of writing

- src/SelfService.Tests/Builders/CapabilityApplicationServiceBuilder.cs
- src/SelfService/Application/CapabilityApplicationService.cs
- src/SelfService/Application/ConfigurationLevelService.cs
- src/SelfService/Application/ICapabilityApplicationService.cs
- src/SelfService/Application/IConfigurationLevelService.cs
- src/SelfService/Configuration/Domain.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityDetailsApiResource.cs
closes dfds/cloudplatform/issues/2522
Is not yet a complete functionality, but in mind of keeping PRs smaller, the actual functions which compute these values will come in a separate PR.
As such, since I still do not know how those functions could fail, there is no error handling implemented yet.
> Endpoint and logic to get the configuration level of a capability

- src/SelfService/Application/KafkaTopicApplicationService.cs
- src/SelfService/Domain/Exceptions/InvalidMessageContractRequestException.cs
- src/SelfService/Infrastructure/Api/Kafka/KafkaTopicController.cs
closes dfds/cloudplatform/issues/2552
None
> Improve error handling in topic schema validation

- src/SelfService.Tests/Application/TestMessageContractValidation.cs
- src/SelfService.Tests/Builders/MessageContractBuilder.cs
- src/SelfService/Application/KafkaTopicApplicationService.cs
closes dfds/cloudplatform/issues/2563
none
> throw exception when trying to evolve schema with pending contract

- src/SelfService/Application/ConfigurationLevelService.cs
* Logic now separates public and private topics
* Returned texts indicate status level
* Removed suggestions
> Level-based messages and public topic awareness

- db/Dockerfile
closes dfds/cloudplatform/issues/2262
none.
> changed Dockerfile to different source of pgup

- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityDetailsApiResource.cs
closes dfds/cloudplatform/issues/2768
- Expose CreatedAt for Capabilities and lists of Capabilities
- Expose CreatedBy for Capabilities and lists of Capabilities
None
> Expose creation details of capabilities

- src/SelfService/Configuration/Domain.cs
- src/SelfService/Domain/Services/MetricsService.cs
- src/SelfService/Infrastructure/Api/Metrics/CapabilityMetrics.cs
- src/SelfService/Infrastructure/Api/UserAction.cs
- src/SelfService/Infrastructure/BackgroundJobs/MetricsUpdater.cs
closes dfds/cloudplatform/issues/2766 
Might've missed some C# idioms since it's been a while, let me know.
Example output:
> Added MetricsService and CapabilityMetrics - Exposing Capability data via metrics data format

- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
closes dfds/cloudplatform/issues/2808
This is a safe start to what Jan may want 🤷
> Remove restrictions for seeing capability recommendations

- db/seed/AzureResource.csv
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
> Fix multithreaded whenall use

- src/SelfService/Domain/Services/AuthorizationService.cs
- src/SelfService/Infrastructure/Api/UserAction.cs
- src/SelfService/Infrastructure/Api/UserImpersonation.cs
- src/SelfService/Program.cs
closes dfds/cloudplatform/issues/2832
Functionality to disable the cloud engineer role permissions
> working cloud engineer permissions

- src/SelfService.Tests/Infrastructure/Api/MembershipApplicationRoutes/when_getting_membership_application_approvals_as_member.cs
- src/SelfService.Tests/Infrastructure/Api/MembershipApplicationRoutes/when_getting_membership_application_for_approver_that_has_NOT_approved.cs
- src/SelfService.Tests/Infrastructure/Api/TestCapabilityMembershipApplicationRoutes.cs
- src/SelfService/Domain/Services/AuthorizationService.cs
- src/SelfService/Domain/Services/IAuthorizationService.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/MembershipApplications/MembershipApplicationController.cs
closes dfds/cloudplatform/issues/2893
delete membership application if the user is cloud engineer
> delete membership application if the user is cloud engineer

- db/migrations/20240715135900_add-table-for-capability-claims.sql
- src/SelfService.Tests/Builders/CapabilityApplicationServiceBuilder.cs
- src/SelfService/Application/CapabilityApplicationService.cs
- src/SelfService/Application/ICapabilityApplicationService.cs
- src/SelfService/Configuration/Domain.cs
- src/SelfService/Domain/Models/CapabilityClaim.cs
- src/SelfService/Domain/Models/CapabilityClaimId.cs
- src/SelfService/Domain/Models/CapabilityClaimOption.cs
- src/SelfService/Domain/Models/ICapabilityCalimRepository.cs
- src/SelfService/Domain/Models/ICapabilityClaimRepository.cs
- src/SelfService/Domain/Models/ICapabilityClaimService.cs
- src/SelfService/Domain/Services/AuthorizationService.cs
- src/SelfService/Domain/Services/IAuthorizationService.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityClaimApiResource.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityClaimListApiResource.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityDetailsApiResource.cs
- src/SelfService/Infrastructure/Api/Capabilities/NewCapabilityClaimRequest.cs
- src/SelfService/Infrastructure/Persistence/CapabilityClaimRepository.cs
- src/SelfService/Infrastructure/Persistence/Converters/CapabilityClaimIdConverter.cs
- src/SelfService/Infrastructure/Persistence/SelfServiceDbContext.cs
- Adds new links to capabilities regarding 'claims'
- Adds endpoints for listing and creating claims for a capability
- Adds authorization checks for claims
- Introduces a claims table
- Available Claims and their descriptions are hard coded into the Service
- It is not currently possible to 'un-claim' something once it has been claimed
> Capability claims

- src/SelfService/Domain/Models/JsonSchemaRepository.cs
- src/SelfService/Domain/Services/ISelfServiceJsonSchemaService.cs
- src/SelfService/Domain/Services/SelfServiceJsonSchemaService.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/JsonSchema/SelfServiceJsonSchemaController.cs
- src/SelfService/Infrastructure/Persistence/JsonSchemaRepository.cs
> remove ability to add schema

- src/SelfService/Infrastructure/Persistence/AzureResourceManifestRepository.cs
Apparently we need this for stuff on the azure side to work
> add subscription-id to generated manifest

- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
closes dfds/cloudplatform/issues/2973
No changes required in frontend
> fix permissions for azure

- src/SelfService/Application/AwsEC2QueriesApplicationService.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
closes dfds/cloudplatform/issues/2975
None
> try, catch, and handle

- src/SelfService/Application/AwsEC2QueriesApplicationService.cs
> use correct roles for vpc permissions

- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
> account.Id is not the Id of the account

- src/SelfService/Domain/Exceptions/InvalidJsonSchemaException.cs
- src/SelfService/Domain/Services/SelfServiceJsonSchemaService.cs
- src/SelfService/Infrastructure/Api/JsonSchema/SelfServiceJsonSchemaController.cs
closes dfds/cloudplatform/issues/2977
None
> Prevent server from crashing on bad json input

- src/SelfService/Domain/Models/JsonSchemaRepository.cs
- src/SelfService/Domain/Services/ISelfServiceJsonSchemaService.cs
- src/SelfService/Domain/Services/SelfServiceJsonSchemaService.cs
- src/SelfService/Infrastructure/Api/JsonSchema/SelfServiceJsonSchemaController.cs
- src/SelfService/Infrastructure/Persistence/JsonSchemaRepository.cs
This was removed to stop schema registry, but it should have nothing to do with that.
> Reintroduce add schema

- src/SelfService/Infrastructure/BackgroundJobs/DeserializationTypes/User.cs
- src/SelfService/Infrastructure/BackgroundJobs/RemoveDeactivatedMemberships.cs
- src/SelfService/Infrastructure/BackgroundJobs/UserStatusChecker.cs
> Hotfix for supporting external users in RemoveDeactivatedMemberships

- src/SelfService.Tests/Builders/ConfigurationLevelServiceBuilder.cs
- src/SelfService/Application/CapabilityApplicationService.cs
- src/SelfService/Application/ConfigurationLevelService.cs
- src/SelfService/Application/ICapabilityApplicationService.cs
- src/SelfService/Domain/Models/ICapabilityClaimRepository.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
- src/SelfService/Infrastructure/Persistence/CapabilityClaimRepository.cs
closes dfds/cloudplatform/issues/3003
I have started the renaming here.
The full rename of Claims -> Self-Assessment will be a separate PR
> Add self-assessment as capability health metrics

- src/SelfService/Domain/Services/AuthorizationService.cs
- src/SelfService/Domain/Services/IAuthorizationService.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
closes dfds/cloudplatform/issues/3011
No change needed in the frontend as it respects the backend
> don't fetch information unless AWS account has been created

- db/seed/SelfAssessmentOption.csv
- db/seed/_order
closes dfds/cloudplatform/issues/3034
None
> Add active SelfAssessmentOption for local development

- src/SelfService/Domain/Models/CapabilityId.cs
closes dfds/cloudplatform/issues/3051
Verify that we are allowed to change the length of the root id
> prevent consecutive dashes leading to random suffix

- db/seed/SelfServiceJsonSchema.csv
Adding two additional tags to match production
> let's match production somewhat

- Dockerfile
- azure-pipelines.yml
- db/migrations/20241125133404_add-selfassessment-status.sql
- global.json
- src/SelfService.Tests/Infrastructure/Api/FakeAuthenticationHandler.cs
- src/SelfService.Tests/SelfService.Tests.csproj
- src/SelfService/Application/CapabilityApplicationService.cs
- src/SelfService/Application/ICapabilityApplicationService.cs
- src/SelfService/Domain/Models/ISelfAssessmentRepository.cs
- src/SelfService/Domain/Models/SelfAssessment.cs
- src/SelfService/Domain/Models/SelfAssessmentStatus.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
- src/SelfService/Infrastructure/Api/Capabilities/SelfAssessmentApiResource.cs
- src/SelfService/Infrastructure/Api/Capabilities/SelfAssessmentRequest.cs
- src/SelfService/Infrastructure/Persistence/SelfAssessmentRepository.cs
- src/SelfService/SelfService.csproj
- src/SelfService/global.json
part of dfds/cloudplatform/issues/3058
Also remove the ability to delete assessments.
> Allow for an enum of self-assessments

- Dockerfile
> update aspnet to match expectations

- db/migrations/20241205132000_add_ecr_uri.sql
- db/seed/ECRRepository.csv
- src/SelfService.Tests/Builders/ECRRepositoryBuilder.cs
- src/SelfService/Application/AwsEcrRepositoryApplicationService.cs
- src/SelfService/Application/AwsMockApplicationService.cs
- src/SelfService/Application/IAwsECRRepositoryApplicationService.cs
- src/SelfService/Domain/Models/ECRRepository.cs
- src/SelfService/Domain/Models/ECRRepositoryId.cs
- src/SelfService/Domain/Services/ECRRepositoryService.cs
closes dfds/cloudplatform/issues/2413
So many horrible hardcodings of AWS Account.
...Something that we already did, unfortunately
> Adding ECR URI to database

- db/seed/AwsAccount.csv
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
> Minor cleanup

- src/SelfService.Tests/Application/TestMembershipApplicationService.cs
- src/SelfService/Application/MembershipApplicationService.cs
closes dfds/cloudplatform/issues/3117
We need a better way of handling erronous events
> Do not crash upon trivial errors

- chart/templates/ingress.yaml
- k8s/ingressroute.yml
> Upgrade Traefik resources to use new API group

- src/SelfService.Tests/Application/TestAwsAccountApplicationService.cs
- src/SelfService/Application/AwsAccountApplicationService.cs
Updates the topdesk message when a new capability account is created.
Part of: https://github.com/dfds/cloudplatform/issues/3150
> Update new capability message

- src/SelfService/Domain/Services/MetricsService.cs
- src/SelfService/Infrastructure/Api/Metrics/CapabilityMetrics.cs
These are the current needs. Let's see if they are enough going forward 🤷
> add additional tags for exportation

- azure-pipelines.yml
Should we simply use `latest instead` ?
> Update pipline OS version

- azure-pipelines.yml
- db/seed/MembershipApplication.csv
- src/SelfService/Application/IInvitationApplicationService.cs
- src/SelfService/Application/InvitationApplicationService.cs
- src/SelfService/Application/MembershipApplicationService.cs
- src/SelfService/Configuration/Domain.cs
- src/SelfService/Domain/Models/IInvitationRepository.cs
- src/SelfService/Domain/Models/IMembershipApplicationRepository.cs
- src/SelfService/Domain/Models/IMembershipRepository.cs
- src/SelfService/Infrastructure/BackgroundJobs/CancelExpiredCapabilityInvitations.cs
- src/SelfService/Infrastructure/BackgroundJobs/CancelExpiredMembershipApplications.cs
- src/SelfService/Infrastructure/BackgroundJobs/CheckMembershipDiscrepancies.cs
- src/SelfService/Infrastructure/Persistence/InvitationRepository.cs
- src/SelfService/Infrastructure/Persistence/MembershipApplicationRepository.cs
- src/SelfService/Infrastructure/Persistence/MembershipRepository.cs
> Fix invitation and application discrepancies

- src/SelfService/SelfService.csproj
In an attempt to fix:
```
System.FormatException: Input string was not in a correct format. Failure to parse near offset 2. Expected an ASCII digit.
at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
at System.Text.StringBuilder.AppendFormat(String format, Object[] args)
at Prometheus.MeterAdapter.TranslateInstrumentDescriptionToPrometheusHelp(Instrument instrument)
at Prometheus.MeterAdapter.OnInstrumentPublished(Instrument instrument, MeterListener listener)
at System.Diagnostics.Metrics.Instrument.Publish()
at System.Diagnostics.Metrics.UpDownCounter`1..ctor(Meter meter, String name, String unit, String description, IEnumerable`1 tags)
at System.Diagnostics.Metrics.Meter.<>c__DisplayClass37_0`1.<CreateUpDownCounter>b__0()
at …
```
> Updated Prometheus libraries from 7.0.0 to 8.2.1

- src/SelfService/Application/InvitationApplicationService.cs
> check status before cancel

- src/SelfService/Configuration/Domain.cs
> do not commit unfinished changes

- src/SelfService/Application/AwsEcrRepositoryApplicationService.cs
> trim values

- src/SelfService.Tests/TestDoubles/StubReleaseNoteRepository.cs
- src/SelfService/Domain/Models/IReleaseNoteRepository.cs
- src/SelfService/Domain/Services/AuthorizationService.cs
- src/SelfService/Domain/Services/IAuthorizationService.cs
- src/SelfService/Domain/Services/IReleaseNoteService.cs
- src/SelfService/Domain/Services/ReleaseNoteService.cs
- src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
- src/SelfService/Infrastructure/Api/ReleaseNotes/ReleaseNoteApiResource.cs
- src/SelfService/Infrastructure/Api/ReleaseNotes/ReleaseNotesController.cs
- src/SelfService/Infrastructure/Persistence/ReleaseNoteRepository.cs
Introduce the removal of release notes
Trying to use the release note history as I think intended.
We could also use delete to clear up the related history... 🤷
> Allow removal of release notes

- src/SelfService/Application/AzureResourceApplicationService.cs
- src/SelfService/Application/IAzureResourceApplicationService.cs
- src/SelfService/Domain/Events/AzureResourceRequested.cs
- src/SelfService/Domain/Models/AzureResource.cs
- src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs
- src/SelfService/Infrastructure/Api/Capabilities/NewAzureResourceRequest.cs
- src/SelfService/Infrastructure/Persistence/AzureResourceManifestRepository.cs
- We need to change the underlying terraform templates, but we are not the owners of this
- How will such a change affect existing templates?
> Send extra arguments to Azure terraform template
