src/SelfService/Domain/Services/MembershipApplicationDomainService.cs
Simpler to understand for the users, less code, and based in as much necessity as the old decision
=> Always require just one approval for membership

k8s/deployment.yml
As part of https://github.com/orgs/dfds/projects/25/views/15?pane=issue&itemId=31593537 quite a few secrets were removed. 
Currently the new selfservice-api deployment Kubernetes manifest has a reference to one of those old secrets. This PR removes that.
As far as I can see, the selfservice-api application itself doesn't make use of it?
=> fix: Removed legacy DB connection string

k8s/ingressroute.yml
The predecessor to _selfservice-api_, _capability-service_, had an IngressRoute that allowed access to the API.
The API at the time was protected with OAuth, and seemingly 99% of selfservice-api is too. I've checked all routes in the openapi spec, and only found one route that wasn't protected (_/apispecs_).
Feel free to raise any concerns.
=> Added additional ingress for selfservice-api

src/SelfService.Tests/Domain/Models/TestKafkaTopicName.cs, src/SelfService/Domain/Models/KafkaTopicName.cs, src/SelfService/Infrastructure/Persistence/Converters/KafkaTopicNameConverter.cs
For context, see: https://github.com/dfds/cloudplatform/issues/1780
Screenshots:
Still denying creation of topic that fails the regex:
Will allow listing/reading topics that fails the regex now:
=> Getting topic names out of database is now less strict in terms of value validation

src/SelfService/Domain/Models/MembershipApplicationStatusOptions.cs, src/SelfService/Infrastructure/Persistence/Converters/MembershipApplicationStatusOptionConverter.cs, src/SelfService/Infrastructure/Persistence/SelfServiceDbContext.cs
closes dfds/cloudplatform/issues/1835
partially
These warnings are self-imposed.
This solution follow the suggestion from the original developers, which is more structured.
Alternatively we could simply remove the obsolete-attribute from the enum, but that would leave us with multiple different implementation styles.
Thoughts?
=> Remove self-imposed obsoletion warning

src/SelfService/Domain/Events/AwsAccountRequested.cs
closes dfds/cloudplatform/issues/1835
partially
AccountID _should_ never be a null value.
I am not 100% certain, so this might break things.
=> Prevent warning for null possibility

db/migrations/20230801113000_add-capability-status.sql, db/seed/Capability.csv, db/seed/Member.csv, db/seed/Membership.csv, db/seed/MembershipApplication.csv, src/SelfService.Tests/Builders/CapabilityBuilder.cs, src/SelfService.Tests/Comparers/CapabilityComparer.cs, src/SelfService/Domain/Models/Capability.cs, src/SelfService/Domain/Models/CapabilityStatusOptions.cs, src/SelfService/Infrastructure/Api/Me/Module.cs, src/SelfService/Infrastructure/Api/Stats/StatsController.cs, src/SelfService/Infrastructure/Persistence/CapabilityRepository.cs, src/SelfService/Infrastructure/Persistence/Converters/CapabilityStatusOptionConverter.cs, src/SelfService/Infrastructure/Persistence/Queries/AadAwsSyncCapabilityQuery.cs, src/SelfService/Infrastructure/Persistence/Queries/CapabilityMembersQuery.cs, src/SelfService/Infrastructure/Persistence/SelfServiceDbContext.cs
closes dfds/cloudplatform/issues/1851
Modifies existing database table and transforms the data
There is no going back from a failure
I have tested this locally, running the migration script against the database produced by the develop-branch using pgAdmin.
This PR is constrained to introducing the capability status and making sure everything works as expected.
Bonus: I changed the seeding scripts so that the 4 main contributors of this repository are automatically members of the dummy-capabilities present during local development
=> Change database schema for capability status

src/SelfService.Tests/Infrastructure/Messaging/TestDafdaSerializationDeserialization.cs, src/SelfService.Tests/Infrastructure/Messaging/TestDomainEventsDafdaDeserialization.cs, src/SelfService/Domain/Events/KafkaClusterAccessGranted.cs, src/SelfService/Domain/Events/KafkaTopicProvisioningHasBegun.cs, src/SelfService/Domain/Events/KafkaTopicProvisioningHasCompleted.cs, src/SelfService/Domain/Events/SchemaRegistered.cs, src/SelfService/Domain/Policies/MarkMessageContractAsProvisioned.cs, src/SelfService/Infrastructure/Messaging/ConsumerConfiguration.cs
closes dfds/cloudplatform/issues/1881
First I reverted the changes to AwsAccountRequested (#34) and then wrote the serialization+deserialization code that correctly replicated the error message seen in the bug. 
Then I added test for all domain events, both for using the parameterless constructor and constructor with parameters.
I also extracted some classes into the directory where the other DomainEvents are.
=> Adding regression test for serialization of DomainEvents

db/migrations/20230816103000_add-capability-modifiedby.sql, db/seed/Capability.csv, src/SelfService.Tests/Application/TestAwsAccountApplicationService.cs, src/SelfService.Tests/Builders/CapabilityBuilder.cs, src/SelfService.Tests/Comparers/CapabilityComparer.cs, src/SelfService.Tests/Infrastructure/Persistence/TestCapabilityRepository.cs, src/SelfService.Tests/TestDoubles/StubCapabilityRepository.cs, src/SelfService/Application/CapabilityApplicationService.cs, src/SelfService/Application/ICapabilityApplicationService.cs, src/SelfService/Configuration/Domain.cs, src/SelfService/Domain/Models/Capability.cs, src/SelfService/Domain/Models/ICapabilityRepository.cs, src/SelfService/Infrastructure/Api/ApiResourceFactory.cs, src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs, src/SelfService/Infrastructure/BackgroundJobs/CheckPendingCapabilityDeletions.cs, src/SelfService/Infrastructure/Persistence/CapabilityRepository.cs
closes dfds/cloudplatform/issues/1870
This is technically enough, but it would be worthwhile knowing who requested the deletion in the first place.
I originally meant to create a table for managing state history like this, but was told not to spend time on this.
Question now is, do we want to extend our `Capability` table with a column for `ModifiedBy` as well?
It is not a hard thing to add, but it may not be the right solution.
On the other hand; It might be a fine solution whilst awaiting the real ownership and state management 🤷 
This (should) solve the ticket, but it feels half-baked. See above question.
=> Send topdesk ticket for longpending deletions

db/migrations/20230824105400_set-modified-by-to-some-value.sql
closes dfds/cloudplatform/issues/1946
Null is not allowed, yet we set it as a default for existing entries.
Let's fill it with a meaningful value
=> remove null values in capabilities modifiedBy

db/seed/Capability.csv, src/SelfService.Tests/Infrastructure/Persistence/TestCapabilityRepository.cs, src/SelfService/Domain/Services/AuthorizationService.cs, src/SelfService/Domain/Services/IAuthorizationService.cs, src/SelfService/Infrastructure/Api/ApiResourceFactory.cs, src/SelfService/Infrastructure/Persistence/CapabilityRepository.cs
closes dfds/cloudplatform/issues/1955
I do not believe that this is the best way to do this;
It is very specific and not easily expandable should we add more states or roles.
However, it _is_ a simple way to do this, following our existing patterns and approaches.
I am all ears for equally simple but better ways of doing this.
We can also move this to the frontend, but I believe it belongs here.
Lastly; Changing this in this way will not impact our current users.
=> Simplest change to allow privileged users access to deleted capabilities

.github/workflows/dependent-issues.yml
its nice to indicate and block one pr from being merged by saying that it is blocked by another
**Example:**
blocked by #11 
or
depends on #11
=> added workflow for dependent issues

src/SelfService.Tests/Infrastructure/Persistence/TestECRRepositoryRepository.cs, src/SelfService/Configuration/Domain.cs, src/SelfService/Domain/Models/IECRRepositoryRepository.cs, src/SelfService/Domain/Services/AuthorizationService.cs, src/SelfService/Domain/Services/ECRRepositoryService.cs, src/SelfService/Domain/Services/IAuthorizationService.cs, src/SelfService/Domain/Services/IECRRepositoryService.cs, src/SelfService/Infrastructure/Api/CustomObjectResults.cs, src/SelfService/Infrastructure/Api/ECRRepositories/ECRRepositoriesController.cs, src/SelfService/Infrastructure/BackgroundJobs/ECRRepositorySynchronizer.cs, src/SelfService/Infrastructure/Persistence/ECRRepositoryRepository.cs
closes dfds/cloudplatform/issues/2028
Contains fix that makes it possible to add/remove ecr into/from database. Was previously broken because of missing db commit.
Also includes an endpoint for triggering it manually. Currently only cloud engineers can make it actually update the database.
**When simply checking:**
**When altering:**
=> Added background service that synchronizes aws and db ECR repositories

src/SelfService.Tests/Infrastructure/Persistence/TestMemberCleaner.cs, src/SelfService.Tests/TestDoubles/StubUserStatusChecker.cs, src/SelfService/Application/DeactivatedMemberCleanerApplicationService.cs, src/SelfService/Infrastructure/BackgroundJobs/IUserStatusChecker.cs, src/SelfService/Infrastructure/BackgroundJobs/UserStatusChecker.cs
closes dfds/cloudplatform/issues/2097
problem was discovered when inspecting production logs:
SetToken was successfully setting the token, but the methods which used the token in the outer scope were behaving as if it wasn't properly set.
Problem was that SetToken was being called synchronously in an async context, which meant the TrySetToken would return without waiting on it, and the UserStatusChecker would thus fail.
=> made it so that we can await SetToken

src/SelfService/Infrastructure/Api/ApiResourceFactory.cs, src/SelfService/Infrastructure/Api/Me/Module.cs
related to dfds/cloudplatform/issues/2231
I had hoped we could avoid linking here, for there is no good spot for it.
It turned out that the non-linking solution was uglier and forced a lot of responsibility unto the frontend so I went back on that desire.
As long as we use _links, then we should at least also be consistent.
This version is easy to expand with future invitation types, so there is that at least.
That is also why it lives on the profile.
=> Follow our linking strategy

src/SelfService.Tests/Infrastructure/Api/TestCapabilityAwsAccountRoutes.cs, src/SelfService/Domain/Services/AuthorizationService.cs, src/SelfService/Infrastructure/Api/ApiResourceFactory.cs
relates dfds/cloudplatform/issues/2253
(Backend part of issue 2253)
I am unsure if this separation has additional effects elsewhere.
I believe it should be good.
Checking for account existence before allowing read seems like a no brainer.
=> Separate reading and writing permission for AWS Accounts.

src/SelfService/Domain/Exceptions/InvalidJsonSchemaException.cs, src/SelfService/Domain/Services/ISelfServiceJsonSchemaService.cs, src/SelfService/Domain/Services/SelfServiceJsonSchemaService.cs, src/SelfService/Infrastructure/Api/JsonSchema/SelfServiceJsonSchemaController.cs
closes dfds/cloudplatform/issues/2313
Added requirement because frontend expects this version and this version is already used for the meta-schema validation
=> Moved validation of schema into service, added requirement for $schema to be equal to newest version

db/seed/Invitation.csv, src/SelfService.Tests/Application/TestInvitationApplicationService.cs, src/SelfService.Tests/Application/TestMembershipApplicationService.cs, src/SelfService.Tests/Builders/MembershipApplicationServiceBuilder.cs, src/SelfService/Application/IMembershipApplicationService.cs, src/SelfService/Application/InvitationApplicationService.cs, src/SelfService/Application/MembershipApplicationService.cs, src/SelfService/Domain/Models/IInvitationRepository.cs, src/SelfService/Domain/Models/Invitation.cs, src/SelfService/Domain/Models/InvitationStatusOptions.cs, src/SelfService/Infrastructure/Persistence/InvitationRepository.cs
closes dfds/cloudplatform/issues/2307
Prevents adding invitations for user-capability combinations which already have active invitations.
When accepting an invitaiton, all active invitations for same user-capability combination are cancelled.
When joining a capability by any means, all invitations for that same user and capability are cancelled.
=> Prevent multiple invitations and existing invitations

src/SelfService/Infrastructure/Api/ApiResourceFactory.cs, src/SelfService/Infrastructure/Api/Capabilities/CapabilityDetailsApiResource.cs
closes dfds/cloudplatform/issues/2333
From doing this task I found that capability resources already returns the json metadata directly, but the frontend uses the getMetadataEndpoint. I have made a task for it dfds/cloudplatform/issues/2357
=> added json metadata to capability list item

src/SelfService.Tests/Application/TestCapabilityApplicationService.cs, src/SelfService/Application/CapabilityApplicationService.cs, src/SelfService/Application/ICapabilityApplicationService.cs, src/SelfService/Infrastructure/Api/ApiResourceFactory.cs, src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs, src/SelfService/Infrastructure/Api/Capabilities/CapabilityDetailsApiResource.cs
closes dfds/cloudplatform/issues/2401
Added new endpoint that I presume will be temporary and removed when we give full control to users of setting json metadata.
The endpoint checks if the metadata in the request only changes properties which are required
=> added new endpoint for changing metadata of required fields

src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs, src/SelfService/Infrastructure/Api/ECRRepositories/ECRRepositoriesController.cs
Had to fix some response types of the api in order to make the autogenerated api client for the CLI to work
=> Fix ecr response type

src/SelfService.Tests/Builders/CapabilityApplicationServiceBuilder.cs, src/SelfService/Application/CapabilityApplicationService.cs, src/SelfService/Application/ICapabilityApplicationService.cs, src/SelfService/Configuration/Domain.cs, src/SelfService/Domain/Models/CapabilityClaim.cs, src/SelfService/Domain/Models/CapabilityClaimId.cs, src/SelfService/Domain/Models/CapabilityClaimOption.cs, src/SelfService/Domain/Models/ICapabilityCalimRepository.cs, src/SelfService/Domain/Models/ICapabilityClaimRepository.cs, src/SelfService/Domain/Models/ICapabilityClaimService.cs, src/SelfService/Domain/Services/AuthorizationService.cs, src/SelfService/Domain/Services/IAuthorizationService.cs, src/SelfService/Infrastructure/Api/ApiResourceFactory.cs, src/SelfService/Infrastructure/Api/Capabilities/CapabilityClaimApiResource.cs, src/SelfService/Infrastructure/Api/Capabilities/CapabilityClaimListApiResource.cs, src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs, src/SelfService/Infrastructure/Api/Capabilities/NewCapabilityClaimRequest.cs, src/SelfService/Infrastructure/Persistence/CapabilityClaimRepository.cs, src/SelfService/Infrastructure/Persistence/Converters/CapabilityClaimIdConverter.cs, src/SelfService/Infrastructure/Persistence/SelfServiceDbContext.cs
Extends the existing suggested solution with the following:
- ClaimsService for wrapping database interactions in additional logic
- ResourceLinks for following our API standard
- Purely URL-based claims adding, rather than sending post-body
- Descriptions to the known claims
- A list of known claims
The idea is to make the frontend completely ignorant of which claims exists, and simply render things.
=> Add resource linking and claim information

db/Dockerfile
We should not depend on 'latest', as this _may_ cause issues if updates to pgup happens that could break things for us
=> lock version of pgup

src/SelfService.Tests/SelfService.Tests.csproj, src/SelfService/Domain/Aspectly/AspectContext.cs, src/SelfService/Domain/Aspectly/AspectOptionsBuilder.cs, src/SelfService/Domain/Aspectly/AspectRegistry.cs, src/SelfService/Domain/Aspectly/AttributeAspectMap.cs, src/SelfService/Domain/Aspectly/IAspect.cs, src/SelfService/Domain/Aspectly/IAspectOptions.cs, src/SelfService/Domain/Aspectly/InterceptPipeline.cs, src/SelfService/Domain/Aspectly/MethodInterceptor.cs, src/SelfService/Domain/Aspectly/PipelineStepFactory.cs, src/SelfService/Domain/Aspectly/PipelineSteps.cs, src/SelfService/Domain/Aspectly/README.md, src/SelfService/Domain/Aspectly/ServiceCollectionExtensions.cs, src/SelfService/Infrastructure/Messaging/OutboxEnqueuerAspect.cs, src/SelfService/Infrastructure/Persistence/TransactionalAspect.cs, src/SelfService/SelfService.csproj
closes dfds/cloudplatform/issues/2913
- Copy Aspectly library code into our project.
- Update EntityFramework versions.
This was the quickest way to claim ownership of Aspectly, instead of rebuilding it.
I still don't necessarily like what it does -- or at least I don't feel it is needed -- but now we can keep it up to date and prevent security issues whilst we use it.
=> Take control of Aspectly functionality

src/SelfService.Tests/Builders/MembershipApplicationServiceBuilder.cs, src/SelfService/Application/IMembershipApplicationService.cs, src/SelfService/Application/MembershipApplicationService.cs, src/SelfService/Domain/Models/IMembershipApplicationRepository.cs, src/SelfService/Domain/Services/AuthorizationService.cs, src/SelfService/Domain/Services/IAuthorizationService.cs, src/SelfService/Infrastructure/Api/ApiResourceFactory.cs, src/SelfService/Infrastructure/Api/Capabilities/MembershipApplicationThatUserCanApproveApiResource.cs, src/SelfService/Infrastructure/Api/Capabilities/MembershipApplicationThatUserCanApproveListApiResource.cs, src/SelfService/Infrastructure/Api/MembershipApplications/MembershipApplicationController.cs, src/SelfService/Infrastructure/Persistence/MembershipApplicationRepository.cs
Issue: https://github.com/dfds/cloudplatform/issues/2929
- Added API endpoint for getting membership requests that the current user can approve or decline
- Updated API endpoint to allow members of Capability to reject membership application
=> Added API endpoints to membershipapplications controller

src/SelfService/Application/CapabilityApplicationService.cs, src/SelfService/Application/ICapabilityApplicationService.cs, src/SelfService/Domain/Models/ICapabilityClaimRepository.cs, src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs, src/SelfService/Infrastructure/Persistence/CapabilityClaimRepository.cs
closes dfds/cloudplatform/issues/3000
This is both a matter of 'building fully functional API's' and a matter of needing this latter -- most likely.
Intentionally at least, we will need this.
We are at a time when it makes sense to do this right instead of quickly.
I would like to create this correctly, when we get to the renaming task
=> allow removal of claims

db/migrations/20240927093951_add-table-for-self-assessment.sql
We have existing data, and thus cannot enforce 'not null' as it is
=> We have existing data without ids

db/seed/KafkaCluster.csv, db/seed/KafkaClusterAccess.csv, db/seed/KafkaTopic.csv, src/SelfService.Tests/Builders/CapabilityApplicationServiceBuilder.cs, src/SelfService.Tests/Infrastructure/Api/ApiApplication.cs, src/SelfService/Application/CapabilityApplicationService.cs, src/SelfService/Application/IKafkaSchemaService.cs, src/SelfService/Application/KafkaSchemaService.cs, src/SelfService/Configuration/Domain.cs, src/SelfService/Domain/Models/KafkaSchema.cs, src/SelfService/Domain/Models/KafkaSchemaMetadata.cs, src/SelfService/Domain/Models/KafkaSchemaParams.cs, src/SelfService/Domain/Models/KafkaSchemaReference.cs, src/SelfService/Domain/Models/KafkaSchemaRule.cs, src/SelfService/Domain/Models/KafkaSchemaRuleSet.cs, src/SelfService/Domain/Queries/IKafkaSchemaQuery.cs, src/SelfService/Domain/Services/IConfluentGatewayService.cs, src/SelfService/Infrastructure/Api/ApiResourceFactory.cs, src/SelfService/Infrastructure/Api/Capabilities/KafkaClusterAccessListApiResource.cs, src/SelfService/Infrastructure/Api/Kafka/KafkaSchemaController.cs, src/SelfService/Infrastructure/Kafka/ConfluentGateway.cs, src/SelfService/Properties/launchSettings.json
Uses new confluent-gateway endpoint to fetch schemas.
Schemas are fetched when requested by the frontend and based on cluster.
No filtering is happening at this time.
=> wip: add confluent schemas via confluent gateway api

src/SelfService/Domain/Models/SelfAssessmentStatus.cs
We use these primarily for  guiding the frontend.
Using a machine-friendly upper-case format we can save some logic and make the frontend communication simpler.
=> this is the way

src/SelfService/Infrastructure/Api/ApiResourceFactory.cs, src/SelfService/Infrastructure/Api/Capabilities/CapabilityController.cs, src/SelfService/Infrastructure/Api/Teams/TeamController.cs
closes dfds/cloudplatform/issues/3107
We expect people to be able to search capabilities by AWS Account ID.
Therefore we should not hide it away.
=> always return aws account id in capability list

src/SelfService/Application/AzureResourceApplicationService.cs
Required to roll out a frontend that does not stop Azure Request Group requests lacking sunset date.
=> sunset date should not be a requirement as it is not used
